[package]
name = "tap-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
octocrab = "0.44.1"
reqwest = "0.12.15"
sha2 = "0.10.9"
tokio = { version = "1.45.0", features = ["full"] }
uuid = { version = "1.16.0", features = ["v4"] }
